# -*- coding: utf-8 -*-
"""Mario

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j0Fnso9w_qoqjsfO8fZRBxOSf6AkXjqR
"""

while True:
    try:
        height = int(input("Height: "))
        if 1 <= height <= 8 and height % 2 == 0:
            break
        print("Please enter an even number between 1 and 8.")
    except ValueError:
        print("Invalid input. Please enter a valid number.")

for row in range(1, height + 1):
    print(" " * (height - row) + "#" * row + "  " + "#" * row)